name: CI

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitignore
    - LICENSE.md
    - README.md
  push:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitignore
    - LICENSE.md
    - README.md

jobs:
  Validation:
    name: GoCloud validation, test and plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::126919054911:role/GitHubRole
        aws-region: us-east-1
    - run: aws sts get-caller-identity
    - name: Initialise Terraform
      run: terraform init
    - name: Check files code formatting
      run: terraform fmt -check -recursive
    - name: Validate the configuration
      run: terraform validate
    - name: Deployment Plan
      run: terraform plan
      
  GoCloud:
    if: ${{ github.event_name == 'push' }}
    name: GoCloud Apply changes
    needs: [Validation]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::126919054911:role/GitHubRole
        aws-region: us-east-1
    - run: aws sts get-caller-identity
    - name: Initialise Terraform
      run: terraform init
    - name: Apply changes to Cloud
      run: terraform apply --auto-approve
